name: MyEssentials
main: com.dah5.myessentials.MyEssentials
version: 1.0
commands:
   myessentials:
      description: Displays plugin author.
      usage: /<command>
   StephEhm93:
      description: Displays girlfriend information.
      usage: /<command>
   saw:
      description: Save all worlds.
      usage: /<command>